[versions]
minecraft = "1.21.1"
fabric_loader = "0.16.14"

fabric_api = "0.116.4+1.21.1"
terraformersmc_modmenu = "11.0.3"
limlib = "12.0.0+1.21.1"
specialmodels = "1.5.0+1.21.1"

cloth = "15.0.140"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

terraformersmc_modmenu = { module = "com.terraformersmc:modmenu", version.ref = "terraformersmc_modmenu" }

ludocrypt_limlib = { module = "net.ludocrypt:limlib", version.ref = "limlib" }
ludocrypt_specialmodels = { module = "net.ludocrypt:specialmodels", version.ref = "specialmodels" }

shedaniel_cloth = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.11-SNAPSHOT" }
